# -*- coding: utf-8 -*-
"""text to image (demo) COPY.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LGKE0D0DRcyyDT6hhL-ZTMtP6c3_TbuU
"""

# https://huggingface.co/blog/stable_diffusion

!pip install diffusers==0.10.2 transformers scipy ftfy accelerate

from diffusers import DiffusionPipeline
import torch

from PIL import Image
import PIL

pipeline = DiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16)
pipeline.to("cuda")

def main():
    while True:
        prompt = input("Please describe the image that you want the AI to draw (type 'q' to terminate the program): \n")

        if prompt.lower() == "q":
            break

        image = pipeline(prompt).images[0]
        image.save(prompt+".png")

    print("The program is successfully terminated!")

if __name__ == "__main__":
    main()